services:
  frontend:
    build:
      context: ./client
      args:
        - REACT_APP_API_URL=http://localhost:5000
    container_name: timecell_frontend
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
    depends_on:
      - backend
    stdin_open: true
    tty: true

  backend:
    build: ./server
    container_name: timecell_backend
    ports:
      - "5000:5000"
    environment:
      - JWT_SECRET=supersecretkey
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=1234
      - DB_NAME=TimeCell_db
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    image: mysql:8
    container_name: timecell_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: TimeCell_db
    volumes:
      - timecell_data:/var/lib/mysql
      - ./server/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: always
  
  # ai:
  #   build: ./ai
  #   container_name: timecell_ai
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - OPENAI_API_KEY=your_openai_api_key_here
  #   depends_on:
  #     - backend
  #   restart: always

volumes:
  timecell_data: