FROM python:3.10-slim
 
ENV PYTHONUNBUFFERED=1
 
RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    libxcb1 \
    libxext6 \
    libx11-6 \
    curl \
    && rm -rf /var/lib/apt/lists/*
 
RUN pip install --upgrade pip
 
WORKDIR /app
 
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
 